### ISSUE TITLE
HDMI aspect ratio incorrect

### ISSUE THREAD

**Issue by M-Walrus** [MiSTer-devel/Arcade-BurningRubber_MiSTer#12]
HDMI visuals do not match up with CRT/Analog output. 

HDMI might be assuming 4:3 when the analog output is slightly different.

**Comment by sorgelig** [comment]
Arcades aren't made originally for TV. Aspect ratio you may see on CRT might be incorrect because adoption of non-TV signal to TV.

**Comment by M-Walrus** [comment]
This is a good point, but I still see that the HDMI aspect ratio is clearly wrong in many games judging by the art assets used.  I see this frequently in Jotego's older arcade cores, but occasionally with official arcade cores like this one as well.

**Comment by paulb-nl** [comment]
The aspect ratio has been changed with commit 71f877cdb0fdfd457d3461424d91abaa02155a9f so this can be closed
