### ISSUE TITLE
Color banding for VGA output in Vertical screen mode

### ISSUE THREAD

**Issue by eskwadrat** [MiSTer-devel/Arcade-BurningRubber_MiSTer#4]
Heavy color banding on VGA output when switched to vertical screen mode. Horizontal mode looks good. Confirmed on 3 different LCD monitors (Dell 20", Microtouch 15", Samsung 19") plus one CRT monitor (Viewsonic 17"). Per core developer feedback (Ash) it's most likely caused by bad timing (too short) for blanking signal (horizontal sync). That confuses the AGC circuits in most monitors, and causes that kind of banding. Similar issue observed for other arcade cores: burning rubber, catacomb, crazy kong, moon cresta, omega, pisces, pooyan, scramble, super glob.

**Comment by tacertain** [comment]
Can you give me some more information and screenshots? I am running through VGA on an old Viewsonic 4:3 LCD display and see no artifacts. Also there is no "horizontal" mode for VGA - that's just an HDMI setting, so I am confused what you mean. Do you mean that changing the HDMI orientation impacts the VGA output? Happy to look into this.

**Comment by paulb-nl** [comment]
This issue can be closed
